# NOTE: Before deploying to a production environment, please review the documentation -> https://aka.ms/self-hosted-gateway-production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: surface-laptop-gw-env
data:
  config.service.endpoint: "https://aisshared.management.azure-api.net/subscriptions/0eb49d19-cb9e-43b2-90e0-ec9298d36203/resourceGroups/aisshared-rg/providers/Microsoft.ApiManagement/service/aisshared?api-version=2021-01-01-preview"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: surface-laptop-gw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: surface-laptop-gw
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true" 
        dapr.io/app-id: "surface-laptop-gw-app"
        dapr.io/app-port: "3500"
        dapr.io/config: "tracing"
      labels:
        app: surface-laptop-gw
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: surface-laptop-gw
        image: mcr.microsoft.com/azure-api-management/gateway:latest
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8081
        readinessProbe:
          httpGet:
            path: /internal-status-0123456789abcdef
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        env:
        - name: config.service.auth
          valueFrom:
            secretKeyRef:
              name: surface-laptop-gw-token
              key: value
        envFrom:
        - configMapRef:
            name: surface-laptop-gw-env
---
apiVersion: v1
kind: Service
metadata:
  name: surface-laptop-gw
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8081
  selector:
    app: surface-laptop-gw