apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pub-sub-orders
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString
    value: <YOUR_SERVICE_BUS_CONNECTION_STRING>
  - name: consumerID
    value: apim-local-gw