apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pub-sub-orders
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString
    value: Endpoint=sb://aisshared-ns.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=El7CUbmf3uVvLFmmqNXzVjW9QG8NPw6V7GEkuRZZv90=
  - name: consumerID
    value: sf-apim-gw-acer-nitro