apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: state-store-orders
spec:
  type: state.azure.tablestorage
  version: v1
  metadata:
  - name: accountName
    value: <YOUR_STORAGE_ACCOUNT_NAME>
  - name: accountKey
    value: <YOUR_STORAGE_ACCOUNT_KEY>
  - name: tableName
    value: orders